### ISSUE TITLE
local 'cpp' package errors due to ArrayBase changes - possible regression? Compile error not helpful.

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/hxcpp#388] opened 2016-03-01 12:49 UTC
Compile with
    -main targets.cpp.AwdCpp

Error: ./src/targets/cpp/AwdCpp.cpp:91:3: error: no type named 'ArrayBase' in namespace 'targets::cpp'; did you mean '::cpp::ArrayBase'?

This error message was misleading.  Had to adjust my internal package names but if this is a new requirement I would expect the compiler to warn me.

Fixed with
    -main targets.cplusplus.AwdCpp

Probably quite a rare issue, but reporting anyway thanks  :)

**Comment by hughsando** [comment] 2016-04-18 13:27
This is caused by having a package directory called "cpp".  The ArrayBase case should be fixed now - since cpp::ArrayBase is no longer used.  I've also checked for others in the cpp namespace.

**Closed by hughsando** 2016-04-18 13:27 UTC
