### ISSUE TITLE
Error compiling hxcpp app on El Capitan, Haxe 3.2.1 and hxcpp 3.2.180

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/hxcpp#324] opened 2015-10-28 18:02 UTC
Hi there,

I'm trying to compile a hxcpp OpenFL app on Mac with the aforementioned OS version. The app is the sample app for `hx-mathml`, which you can find here: https://github.com/sciencePowerApp/hx-mathml.

haxeui-rich-text: [0.1.2]
haxeui: [1.7.18]
openfl-tools: [1.0.10]
openfl: 3.3.8 [3.3.9]
lime: 2.6.8 [2.6.9]

While trying to compile with `openfl build mac`, I get the following error:

```
Error: ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:161:15: error: allocating an object of abstract class type '::haxe::ui::toolkit::core::interfaces::IStyleableDisplayObject_delegate_<ItemRenderer_obj>'
        { return new ::haxe::ui::toolkit::core::interfaces::IStyleableDisplayObject_delegate_< ItemRenderer_obj >(this); }
                     ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:127:16: note: unimplemented pure virtual method 'addEventListener' in 'IStyleableDisplayObject_delegate_'
                virtual Void addEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture,hx::Null< int >  priority,hx::Null< bool >  useWeakReference)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:128:17: note: unimplemented pure virtual method 'addEventListener_dyn' in 'IStyleableDisplayObject_delegate_'
virtual Dynamic addEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:129:16: note: unimplemented pure virtual method 'dispatchEvent' in 'IStyleableDisplayObject_delegate_'
                virtual bool dispatchEvent( ::openfl::_legacy::events::Event event)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:130:17: note: unimplemented pure virtual method 'dispatchEvent_dyn' in 'IStyleableDisplayObject_delegate_'
virtual Dynamic dispatchEvent_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:131:16: note: unimplemented pure virtual method 'hasEventListener' in 'IStyleableDisplayObject_delegate_'
                virtual bool hasEventListener( ::String type)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:132:17: note: unimplemented pure virtual method 'hasEventListener_dyn' in 'IStyleableDisplayObject_delegate_'
virtual Dynamic hasEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:133:16: note: unimplemented pure virtual method 'removeEventListener' in 'IStyleableDisplayObject_delegate_'
                virtual Void removeEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:134:17: note: unimplemented pure virtual method 'removeEventListener_dyn' in 'IStyleableDisplayObject_delegate_'
virtual Dynamic removeEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:135:16: note: unimplemented pure virtual method 'willTrigger' in 'IStyleableDisplayObject_delegate_'
                virtual bool willTrigger( ::String type)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:136:17: note: unimplemented pure virtual method 'willTrigger_dyn' in 'IStyleableDisplayObject_delegate_'
virtual Dynamic willTrigger_dyn()=0;
                ^
./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:165:15: error: allocating an object of abstract class type '::haxe::ui::toolkit::core::interfaces::IComponent_delegate_<ItemRenderer_obj>'
        { return new ::haxe::ui::toolkit::core::interfaces::IComponent_delegate_< ItemRenderer_obj >(this); }
                     ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:127:16: note: unimplemented pure virtual method 'addEventListener' in 'IComponent_delegate_'
                virtual Void addEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture,hx::Null< int >  priority,hx::Null< bool >  useWeakReference)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:128:17: note: unimplemented pure virtual method 'addEventListener_dyn' in 'IComponent_delegate_'
virtual Dynamic addEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:129:16: note: unimplemented pure virtual method 'dispatchEvent' in 'IComponent_delegate_'
                virtual bool dispatchEvent( ::openfl::_legacy::events::Event event)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:130:17: note: unimplemented pure virtual method 'dispatchEvent_dyn' in 'IComponent_delegate_'
virtual Dynamic dispatchEvent_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:131:16: note: unimplemented pure virtual method 'hasEventListener' in 'IComponent_delegate_'
                virtual bool hasEventListener( ::String type)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:132:17: note: unimplemented pure virtual method 'hasEventListener_dyn' in 'IComponent_delegate_'
virtual Dynamic hasEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:133:16: note: unimplemented pure virtual method 'removeEventListener' in 'IComponent_delegate_'
                virtual Void removeEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:134:17: note: unimplemented pure virtual method 'removeEventListener_dyn' in 'IComponent_delegate_'
virtual Dynamic removeEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:135:16: note: unimplemented pure virtual method 'willTrigger' in 'IComponent_delegate_'
                virtual bool willTrigger( ::String type)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:136:17: note: unimplemented pure virtual method 'willTrigger_dyn' in 'IComponent_delegate_'
virtual Dynamic willTrigger_dyn()=0;
                ^
./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:171:15: error: allocating an object of abstract class type '::haxe::ui::toolkit::core::interfaces::IStateComponent_delegate_<ItemRenderer_obj>'
        { return new ::haxe::ui::toolkit::core::interfaces::IStateComponent_delegate_< ItemRenderer_obj >(this); }
                     ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:127:16: note: unimplemented pure virtual method 'addEventListener' in 'IStateComponent_delegate_'
                virtual Void addEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture,hx::Null< int >  priority,hx::Null< bool >  useWeakReference)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:128:17: note: unimplemented pure virtual method 'addEventListener_dyn' in 'IStateComponent_delegate_'
virtual Dynamic addEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:129:16: note: unimplemented pure virtual method 'dispatchEvent' in 'IStateComponent_delegate_'
                virtual bool dispatchEvent( ::openfl::_legacy::events::Event event)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:130:17: note: unimplemented pure virtual method 'dispatchEvent_dyn' in 'IStateComponent_delegate_'
virtual Dynamic dispatchEvent_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:131:16: note: unimplemented pure virtual method 'hasEventListener' in 'IStateComponent_delegate_'
                virtual bool hasEventListener( ::String type)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:132:17: note: unimplemented pure virtual method 'hasEventListener_dyn' in 'IStateComponent_delegate_'
virtual Dynamic hasEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:133:16: note: unimplemented pure virtual method 'removeEventListener' in 'IStateComponent_delegate_'
                virtual Void removeEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:134:17: note: unimplemented pure virtual method 'removeEventListener_dyn' in 'IStateComponent_delegate_'
virtual Dynamic removeEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:135:16: note: unimplemented pure virtual method 'willTrigger' in 'IStateComponent_delegate_'
                virtual bool willTrigger( ::String type)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:136:17: note: unimplemented pure virtual method 'willTrigger_dyn' in 'IStateComponent_delegate_'
virtual Dynamic willTrigger_dyn()=0;
                ^
./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:173:15: error: allocating an object of abstract class type '::haxe::ui::toolkit::core::interfaces::IDisplayObjectContainer_delegate_<ItemRenderer_obj>'
        { return new ::haxe::ui::toolkit::core::interfaces::IDisplayObjectContainer_delegate_< ItemRenderer_obj >(this); }
                     ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:127:16: note: unimplemented pure virtual method 'addEventListener' in 'IDisplayObjectContainer_delegate_'
                virtual Void addEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture,hx::Null< int >  priority,hx::Null< bool >  useWeakReference)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:128:17: note: unimplemented pure virtual method 'addEventListener_dyn' in 'IDisplayObjectContainer_delegate_'
virtual Dynamic addEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:129:16: note: unimplemented pure virtual method 'dispatchEvent' in 'IDisplayObjectContainer_delegate_'
                virtual bool dispatchEvent( ::openfl::_legacy::events::Event event)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:130:17: note: unimplemented pure virtual method 'dispatchEvent_dyn' in 'IDisplayObjectContainer_delegate_'
virtual Dynamic dispatchEvent_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:131:16: note: unimplemented pure virtual method 'hasEventListener' in 'IDisplayObjectContainer_delegate_'
                virtual bool hasEventListener( ::String type)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:132:17: note: unimplemented pure virtual method 'hasEventListener_dyn' in 'IDisplayObjectContainer_delegate_'
virtual Dynamic hasEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:133:16: note: unimplemented pure virtual method 'removeEventListener' in 'IDisplayObjectContainer_delegate_'
                virtual Void removeEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:134:17: note: unimplemented pure virtual method 'removeEventListener_dyn' in 'IDisplayObjectContainer_delegate_'
virtual Dynamic removeEventListener_dyn()=0;
                ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:135:16: note: unimplemented pure virtual method 'willTrigger' in 'IDisplayObjectContainer_delegate_'
                virtual bool willTrigger( ::String type)=0;
                             ^
include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:136:17: note: unimplemented pure virtual method 'willTrigger_dyn' in 'IDisplayObjectContainer_delegate_'
virtual Dynamic willTrigger_dyn()=0;
                ^
4 errors generated.
```

Could it be something related to this specific version of hxcpp? Any insights appreciated.

**Comment by thomasuster** [comment] 2015-10-28 18:43
Please try this approach to narrow it down...

My a guess at what library is causing the problem, you currently thinking hxcpp.
1) Create an excell sheet with a range of hxcpp versions (http://nmehost.com/hxcpp/)
2) ```haxelib install ~/Downloads/hxcpp.version.seomthign.zip```
3) Run our test script (This could be deleting your export directory and rebuilding your project for mac)
4) Record wether or not that test failed or passed for that hxcpp version

Eventually you'll be able to find the two commits where this passed and failed.

I also HIGHLY recommend you do this an an alternate computer. So you can keep doing whatever you do on your normal computer uninterrupted.

**Comment by madrazo** [comment] 2015-10-28 21:51
Yes, the problem is since haxe 3.2.1 https://github.com/ianharrigan/haxeui/issues/282 . With 3.2.0 works fine

**Comment by thomasuster** [comment] 2015-10-28 21:58
Sounds like it's a haxe issue then?

**Comment by fullofcaffeine** [comment] 2015-10-28 22:02
Yeah, looks like this is the issue https://github.com/HaxeFoundation/haxe/issues/4454. Still open at the time of this writing.

**Comment by hughsando** [comment] 2015-11-05 14:14
I think the reference should be to
https://github.com/HaxeFoundation/haxe/issues/4343, and should be fixed.

**Closed** 2016-03-02 15:31 UTC
