### ISSUE TITLE
Unicode problem - Regression??

### ISSUE THREAD

**Issue by aW4KeNiNG** [HaxeFoundation/hxcpp#831] opened 2019-07-13 14:58 UTC
Hi.

I'm getting text related problems in 2 applications. It worked previously with Haxe 4-rc2 and hxcpp 4.0.8, but it has troubles with Haxe 4-rc3 (or last build) and hxcpp 4.0.19 (or last git version).

**App 1** (OpenFL): it reads a text file to fill the text on screen (it uses i18n and several files for each language).

Result Haxe 4 rc2 + hxcpp 4.0.8:

![image](https://user-images.githubusercontent.com/1063719/61172836-c32bac80-a58a-11e9-8d30-ce8a23e99ab1.png)

Result Haxe 4 rc3 or latest version + hxcpp 4.0.19 or git version (you can see missing letters too):

![image](https://user-images.githubusercontent.com/1063719/61172945-4e597200-a58c-11e9-851d-871a61726291.png)

**App 2** (command line app): It uses a third party C++ library (with externs) to open image files. It was working previosly with Haxe 4 rc2, but I had a problem with `Sys.getEnv("USERPROFILE")`. It returned wrong characters if the username had non-ascii characters. So I saw that bug fixed in Haxe 4 rc3 and the problem was fixed. But now I can't read images from command line. I had problems sending unicode characters from outside, so I used an `encodeUri` method externally and `StringTools.urlDecode` in the haxe side, working in rc2. It isn't working in rc3.

I can replicate the problem with the next code (you need to create a file with the "Test様.txt" name):

```
var uri:String = StringTools.urlDecode("Test%E6%A7%98.txt");
var st:cpp.StdString = cpp.StdString.ofString(uri);
trace(uri, st.toString());
var file:FileInput = File.read(st.toString());
var b = file.readAll();
file.close();
trace(b.length);
```

Result rc2 + 4.0.8:

```
XiaomiMijiaHDRTest01µºÿ.jpg,XiaomiMijiaHDRTest01µºÿ.jpg
5528724
```

Result rc3 + 4.0.19:

```
XiaomiMijiaHDRTest01æ§~.jpg,X
Error: [file_open,X
```

I'm using Windows 10.

**Comment by ncannasse** [comment] 2019-07-16 08:07
Ping @Aurel300

**Comment by Aurel300** [comment] 2019-07-16 13:05
For app 1, this might be related to OpenFl? It would be best if you could provide a minimal project that demonstrates the issue.

For app 2, the results you show have "XiaomiMijiaHDRTest01" in the string, but I assume you just changed all that to "Test" to reduce the example. I can see that rc2 succeeds in reading the file, but clearly outputs the wrong string (`µºÿ` instead of `様`).

I can confirm there seems to be a problem with `cpp.StdString`, I can reproduce on OS X. But why are you using that class at all?

```haxe
var a = "Test様.txt";
var b = StringTools.urlDecode("Test%E6%A7%98.txt");
var c = cpp.StdString.ofString(b);
trace(a, b, c.toString());
trace(sys.io.File.getContent(a));
trace(sys.io.File.getContent(b));
trace(sys.io.File.getContent(c.toString()));
```

For me (again on OS X) this outputs:

```
Main.hx:6: Test様.txt,Test様.txt,T
Main.hx:7: hello
Main.hx:8: hello
Error : [file_contents,T
```

I.e. both the string literal and the URL-decoded versions work, but `StdString` does not. Could you confirm this is the result for you as well? I will not have access to a windows VM until tomorrow.

**Comment by aW4KeNiNG** [comment] 2019-07-16 13:33
I will try to get some minimal example with OpenFL in a few days.

App 2: The wrong string is because I'm using cmd and I didn't change to a Unicode font. Because of that the print message is wrong, but internally it works.

I need to use cpp.StdString because I'm using an external C++ library, so I need to send the string with that class.

The output with that code is the same:

```
Main.hx:7: Testæ§~.txt,Testæ§~.txt,T
Main.hx:8: hello!!
Main.hx:9: hello!!
Error: [file_contents,T
```

**Comment by Aurel300** [comment] 2019-07-22 17:34
I'll check what goes wrong with the `cpp.StdString` conversion. As for the `akifox-asynchttp` library, it might be best to raise the issue in the library repo. Until #8570 is merged there probably won't be a way to do binary HTTP requests. This must have broken during the Unicode-ning and unfortunately HTTP is not unit tested much / at all.

**Comment by hughsando** [comment] 2019-07-23 01:06
The problem with StdString seems to be in the hxcpp header, where it constructs from the "__s", rather than the utf8_str.

**Comment by aW4KeNiNG** [comment] 2019-08-27 12:30
I can confirm the PR fixes the App 2 problem. The App 1 could be a OpenFL problem, I need to build a minimal example.

**Comment by aW4KeNiNG** [comment] 2019-09-11 11:24
Here minimum example in OpenFL with the problem using Haxe 4 rc4 + hxcpp 4.0.52 + openfl 8.9.4 + lime 2.6.2

Code:

```
package;

import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFieldAutoSize;


class Main extends Sprite {
		
	public function new () {
		
		super ();
		
		stage.color = 0xA0A0A0;

		var textField = new TextField();				
		textField.width = 700;
		textField.multiline = true;
		textField.wordWrap = true;
		textField.autoSize = TextFieldAutoSize.NONE;
		
		textField.text = "Inicie sesión como usuario";
		
		addChild (textField);
	}
}
```

Project: https://www.dropbox.com/s/uwi7azysrxae9to/openfl_text_problem.zip?dl=0

Windows: `openfl test windows`

![image](https://user-images.githubusercontent.com/1063719/64693193-fe692f80-d496-11e9-8485-b2ac4dc69250.png)


HTML5: `openfl test html5`

![image](https://user-images.githubusercontent.com/1063719/64693218-0cb74b80-d497-11e9-9107-de2aae170637.png)

**Comment by aW4KeNiNG** [comment] 2019-09-11 11:40
Maybe @jgranick can confirm if it is a hxcpp or openfl related problem.

**Comment by RealyUniqueName** [comment] 2019-09-11 13:57
That looks like an OpenFL issue. What do you get if you write the same string into a file or print it into a terminal with unicode support?

**Comment by aW4KeNiNG** [comment] 2019-09-11 14:08
It is fine. 

The problem only occurs with haxe 4 >= rc3. With rc2 the text is drawn correctly.

**Comment by MSGhero** [comment] 2019-09-15 02:24
I actually can't even compile your example when I have the `ó`. It's fine if I remove it. Latest OpenFL and Lime, rc4 and rc5, hxpp 4.0.52.
```
Error: Main.cpp
./src/Main.cpp(40) : error C2022: '62603' : too big for character
./src/Main.cpp(40) : error C2065: 'u' : undeclared identifier
./src/Main.cpp(40) : error C2143: syntax error : missing ')' before 'string'
./src/Main.cpp(40) : error C2143: syntax error : missing '(' before 'string'
./src/Main.cpp(40) : error C2022: '6113' : too big for character
./src/Main.cpp(40) : error C2022: '32816' : too big for character
./src/Main.cpp(40) : error C2070: 'unknown-type': illegal sizeof operand
./src/Main.cpp(40) : error C2059: syntax error : ')'
```

**Comment by MSGhero** [comment] 2019-09-27 00:58
Confirmed OpenFL issue

**Closed** 2020-02-29 03:08 UTC
