### ISSUE TITLE
Int is wrongly returned as null instead of the true value

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#175] opened 2015-02-23 20:20 UTC
I'm not sure if this is a Haxe or an HXCPP-related problem, but I'll go ahead and post here.

https://github.com/openfl/openfl/commit/216ced76dc99c5ea57a90b4d7a7ccb53dcca1780

Before this change, the following code returned "null" on the C++ target instead of 16384 as expected:

```haxe
trace (GL.getParameter (GL.MAX_TEXTURE_SIZE));
```

When you return a CFFI call directly from the inline function, it works properly, but when it becomes stored as a Dynamic return value, it then evalues to null instead of the proper integer value.

Would this be resolved by a strongly-typed CFFI signature, or do you have other recommendations for guarding against this in the future?

**Comment by hughsando** [comment] 2015-02-23 23:47
So the problem is with before the change (red/removed code)?  I guess the return from a switch in an inline function could be causing some issues - a trace on the value would probably show this.  Does removing the inline help? 
It may also be helpful to look at the generated code - this would give some idea of what is going on - with inferred types etc.

**Comment by thomasuster** [comment] 2015-03-03 19:31
Tried it.. HXCPP 64dfadb4c0a5d9659f9eddf1606a53a703f0c02e, Haxe 3.1.3, openFL 2.2.7

MacBook:hxcpp_175 thomasuster$ openfl test mac
Main.hx:18: null

https://github.com/thomasuster/hxcpp_175

@jgranick What am I miss?

**Comment by hughsando** [comment] 2015-03-11 12:31
I'm going to close this one.  If you have a specific example of the issue, please reopen it.

**Closed by hughsando** 2015-03-11 12:31 UTC

**Comment by jgranick** [comment] 2015-03-11 15:31
I think the issue is that the Int return is evaluted as a Dynamic value, either an Int value evaluated as a Dynamic in this way becomes a "null" object instead of an Int, or perhaps in this scenario, the Int value is 0, so it's treated as NULL due to it's value.
