### ISSUE TITLE
Valid cast leads to null object

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/hxcpp#173] opened 2015-02-20 02:03 UTC
```haxe
class X1 implements Y1 {
	public function new () {}
}

interface Y1 extends Z1 {}

interface Z1 {}

class Test {

	public static function main()
	{
		// this fails
		var z:Z1 = new X1(); 

		trace(z); // traces null

		// it works in two steps
		var z:Y1 = new X1();
		var z:Z1 = z;
		trace(z) // traces valid object

        }
}
```

**Comment by ncannasse** [comment] 2015-02-20 08:30
Ouch. Is that a regression wrt 3.1.3 ?

**Comment by hughsando** [comment] 2015-02-20 08:56
Regression since yesterday - should be fixed.

**Comment by Simn** [comment] 2015-02-20 08:58
I'm surprised our tests miss that. We should make sure it is covered in the unit tests.

**Comment by Simn** [comment] 2015-02-20 09:49
I have added a test.

@hughsando: If you close a hxcpp issues and feel adding a test is worthwhile/viable you can simply add it to https://github.com/HaxeFoundation/haxe/tree/development/tests/unit/src/unit/hxcpp_issues

**Closed by Simn** 2015-02-20 09:49 UTC
