### ISSUE TITLE
cppia unit test is failing on Linux build

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/hxcpp#348] opened 2015-12-29 12:23 UTC
Look like there are changes in the haxe repo that causes the cppia unit test to fail on Linux builds. The build of the latest commit succeed a few days ago but failed for the rebuild today.

**Comment by Simn** [comment] 2015-12-29 12:23
That's probably my fault.

**Comment by Simn** [comment] 2015-12-29 12:33
How do I test this on Windows? I'm looking at

```
C:\GitHub\haxe\tests\unit>haxelib run hxcpp unit.cppia
'"""C:/GitHub/hxcpp/bin/Windows/Cppia.exe"""' is not recognized as an internal or external command, operable program or batch file.
```

P.S.: Shouldn't unit.cppia go to the bin directory?

**Comment by andyli** [comment] 2015-12-29 12:45
umm... I got similar error on my local machine..
It looks like it is caused by https://github.com/HaxeFoundation/haxe/issues/3603, but I'm not sure why it ran correctly on AppVeyor.

**Comment by Simn** [comment] 2015-12-29 12:48
C:/GitHub/hxcpp/bin/Windows/Cppia.exe genuinely doesn't exist though. How is it built?

**Comment by andyli** [comment] 2015-12-29 12:51
Ah... indeed.
I think it is project/compile-cppia.hxml -> https://github.com/HaxeFoundation/hxcpp/blob/master/.travis.yml#L26
Trying now.

**Comment by Simn** [comment] 2015-12-29 12:54
Aaah, that helps. And yes I can reproduce the crash. Bisecting now!

**Comment by Simn** [comment] 2015-12-29 13:20
Looks like cppia is a bit sensitive at the moment. It doesn't like the analyzer transformation at all (I would really like to figure out why), but at the same time it doesn't properly deal with `try` in value places. I will try to figure out why the analyzer is causing trouble with it as this now actually blocks https://github.com/HaxeFoundation/haxe/pull/4746.

**Comment by hughsando** [comment] 2015-12-29 13:56
I think I disabled the analyzer for cppia because, unlike cpp, it has
complete control over the order of operations, and therefore does not need
any of the reorder code.  Also, unlike cpp, all the extra temp variables
that assign to other temp variables etc do not get optimized away by a
sophisticated c++ compiler and simply make the file bigger and slower.
That said, if the optimizer can generate code that cppia does not like, you
can probably create similar code by hand that would behave similarly, and
in this sense it would not be a regression.  Although, cppia might rely on
certain type information that becomes subtly different when the analyzer is
used.

**Comment by Simn** [comment] 2015-12-29 14:15
Is there a debug mode that tells me a bit more than "segmentation fault"?

I can adapt all `platform = Cpp` checks in the analyzer to exclude Cppia. This should actually reduce the output size quite a bit.

**Comment by Simn** [comment] 2015-12-29 14:50
Actually making that change fixes the crash!

The only failing test I get now comes from this:

```
trace(StringTools.isEof(StringTools.fastCodeAt("abc", 3)));
```

Without the analyzer the dump reads:

```
[Var c(149):Int]
	[Call:Int]
		[Field:Int -> Unknown<0>]
			[Const:String] "abc"
			[FDynamic:Int -> Unknown<0>] cca
		[Const:Int] 3
[Binop:Bool]
	[Local c(149):Int]
	==
	[Const:Int] 0

```

With the analyzer:

```
[Call:Int]
	[Field:Int -> Unknown<0>]
		[Const:String] "abc"
		[FDynamic:Int -> Unknown<0>] cca
	[Const:Int] 3
==
[Const:Int] 0
```

This suggests that Cppia actually relies on the temp var being generated for this case.

**Comment by Simn** [comment] 2016-01-04 11:56
I'm not sure what to do here because the AST looks fine to me.

**Comment by Simn** [comment] 2016-01-04 12:36
Looks like it crashes again due to a test I've added. I could reduce it to this:

```haxe
private abstract O(Int) {
	public inline function get():Int return this;
}

class Main {
	static function main() {
		var o:{?v:O} = {};
		o.v.get();
	}
}
```

Dump:

```
class Main{
	static main(method) : Void -> Void

	 = [Function:Void -> Void]
		[Block:Int]
			[Var o(141):{ ?v : Null<_Main.O> }] [ObjectDecl:{ }]
			[Var this1(143):Int]
				[Field:Null<_Main.O>]
					[Local o(141):{ ?v : Null<_Main.O> }]
					[FAnon:Null<_Main.O>] v

}
```

Cppia:

```
CPPIB
24
0 
4 main
1 o
5 this1
1 v
2 is
1 t
12 __instanceof
8 instance
5 value
1 c
6 string
1 s
4 null
8 toString
3 int
1 x
7 __int__
8 parseInt
17 __hxcpp_parse_int
10 parseFloat
19 __hxcpp_parse_float
6 random
13 __hxcpp_irand
10
0 
6 ::Main
4 Void
7 Dynamic
3 int
5 ::Std
4 bool
7 ::Class
8 ::String
5 Float
2
D
```

Does that tell you anything?

**Comment by hughsando** [comment] 2016-01-04 14:27
This is crashing on windows with the current haxe, so I will have a look
now.

**Comment by hughsando** [comment] 2016-01-04 15:18
I have committed a change which should mimic the c++ behaviour - that is,
silently convert null to zero in this case (and like it does in other
cases).
I guess on as3/Js you might end up with Nan or undefined? Or maybe this is
handled explicitly in the backend.

FYI, if you compile cppia with -debug, the output.cppia is more readable,
and should match the dump file quite closely.

**Comment by Simn** [comment] 2016-01-05 09:06
Looks like your latest commit fixed the failing eof test. Now everything passes again, thanks!

**Closed by Simn** 2016-01-05 09:06 UTC

**Comment by hughsando** [comment] 2016-01-05 12:37
I have a new laptop, and finally got ocaml installed (man, that was
frustrating - can't wait for self-hosting haxe) so should be able to do
faster haxe dev again.
