### ISSUE TITLE
Android Compile issue

### ISSUE THREAD

**Issue by MAJigsaw77** [HaxeFoundation/hxcpp#998] opened 2022-06-10 16:28 UTC
im trying to compile an app and it keeps crashing with this 
`/home/runner/haxelib/hxcpp/4,2,1/include/hxcpp.h:23:13: fatal error: 'typeinfo' file not found
   #include <typeinfo>
            ^~~~~~~~~~
1 error generated.
Error: Could not create PCH` is there a way to fix this?

**Comment by justin-espedal** [comment] 2022-06-14 08:32
This may be caused by using an unsupported NDK. Which NDK are you using to build with? Until https://github.com/HaxeFoundation/hxcpp/pull/992 is merged, the highest supported version is NDK 21e.

**Closed** 2023-04-21 04:55 UTC
